### ISSUE TITLE
Error in urdf parsing

### ISSUE THREAD

**Issue by kappa95** [ros2/urdf#22]
Hi I am following the ROS2 tutorial regarding the urdf: [ros2-foxy-urdf-tutorial](https://docs.ros.org/en/foxy/Tutorials/URDF/Using-URDF-with-Robot-State-Publisher.html). I copied and pasted the URDF linked in the tutorial and after i found the error i tried also to substitute each number in the format: -.number into -0.number but nothing changes.
After using the command: `rviz2 -d ./src/urdf_tutorial/urdf/r2d2.rviz` 

The error that I get is this:
```bash
[INFO] [1616842551.318422714] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [1616842551.318632813] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[INFO] [1616842551.347345810] [rviz2]: Stereo is NOT SUPPORTED
Parsing robot urdf xml string.
Error:   length [.5] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [axis]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.6] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [body]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   radius [.4] is not a valid float: stod
         at line 126 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [head]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.2] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [rod]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   lower value (-.5) is not a float: stod
         at line 130 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   Could not parse limit element for joint [tilt]
         at line 565 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   joint xml is not initialized correctly
         at line 206 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/model.cpp

```
And in Rviz is now shown the model but only the TFs moving as shown in the following pic:
![Schermata da 2021-03-27 11-09-46](https://user-images.githubusercontent.com/42738531/112718621-80dc0780-8ef4-11eb-9dcd-dc02de48dac2.png)

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04 Focal 64bit
- Installation type:
  -  Installed directly from debian package as in the [guide](https://docs.ros.org/en/foxy/Installation/Linux-Install-Debians.html)

**Comment by clalancette** [comment]
Please don't open the same issue on multiple repositories; it splits the conversation.  Closing this one in favor of https://github.com/ros2/ros2_documentation/issues/1277
