### ISSUE TITLE
/URDF  CMake Error at CMakeLists.txt:97 (pluginlib_enable_plugin_testing) [Foxy]

### ISSUE THREAD

**Issue by newcanopies** [ros2/urdf#24]
## Bug report

# env
  - Ubuntu 20.04 / Foxy
  - binaries

#### Steps to reproduce issue

clone _ros2 branch_ of `ros2/urdf` to ws_ROS2/src
rosdep update 
colcon build --packages-select `urdf_parser_plugin` `urdf` sdformat_urdf --event-handlers console_cohesion+

```
Finished <<< urdf_parser_plugin [11.9s]
Starting >>> urdf
[Processing: urdf]
--- output: urdf
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ament_cmake_ros: 0.9.1 (/opt/ros/foxy/share/ament_cmake_ros/cmake)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.5", minimum required is "3")
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Found pluginlib: 2.5.3 (/opt/ros/foxy/share/pluginlib/cmake)
-- Found urdf_parser_plugin: 2.5.1 (/home/user/ws_ROS2_sdfurdf/install/urdf_parser_plugin/share/urdf_parser_plugin/cmake)
-- Found TinyXML2: /usr/lib/x86_64-linux-gnu/libtinyxml2.so
-- Found ament_cmake_cppcheck: 0.9.6 (/opt/ros/foxy/share/ament_cmake_cppcheck/cmake)
-- Found ament_cmake_cpplint: 0.9.6 (/opt/ros/foxy/share/ament_cmake_cpplint/cmake)
-- Found ament_cmake_google_benchmark: 0.9.8 (/opt/ros/foxy/share/ament_cmake_google_benchmark/cmake)
-- Found ament_cmake_lint_cmake: 0.9.6 (/opt/ros/foxy/share/ament_cmake_lint_cmake/cmake)
-- Found ament_cmake_uncrustify: 0.9.6 (/opt/ros/foxy/share/ament_cmake_uncrustify/cmake)
CMake Error at CMakeLists.txt:97 (pluginlib_enable_plugin_testing):
  Unknown CMake command "pluginlib_enable_plugin_testing".

```

#### Additional information

I cloned the ros2 branch as it is more updated than the foxy branch. The ros2 branch `urdf_parser_plugin` did build.
But `urdf` package failed at https://github.com/ros2/urdf/blob/233cd1a486dd2b7c7a2af265279002b3ea50b24e/urdf/CMakeLists.txt#L97
 It's unclear why ros2-branch urdf package is not compatible with foxy. I would like to understand this better.

Checking out the Foxy branch completed the `urdf` build.

**Comment by clalancette** [comment]
Generally, you need to match the branch with the release you are using.  We don't guarantee any compatibility between the latest branches and the already released distributions.

I'm not entirely sure why it is failing in this case, but likely some changes to pluginlib caused the issue.  This is more of a question than something to change here, so I'm going to close this out.
