### ISSUE TITLE
relationship between urdf, urdfdom, urdfdom_headers?

### ISSUE THREAD

**Issue by bsoe-flexiv** [ros2/urdf#29]
What is the relationship between these three package/repo?
1. urdfdom_headers
2. urdfdom
3. urdf

**Comment by clalancette** [comment]
There is a diagram of their relationship at https://github.com/ros/urdf/blob/melodic-devel/README.md (we should really port this over to the ROS 2 fork).

For questions like this, please ask them over at https://answers.ros.org, which is our central question-and-answers site.  Closing.
