### ISSUE TITLE
Using .xacro in launch files

### ISSUE THREAD

**Issue by ghost** [ros2/urdf#5]
Hello all

I wondered if it is possible to use .xacro files inside a ROS2 launchfile? In ROS, I use them a lot and it would be much work to transform them all to standard urdf.
Also I wasn't sure where to open this issue - here or in the /launch repo.

Thank you (:

**Comment by mikaelarguedas** [comment]
the [xacro package](https://github.com/ros/xacro) has not been ported to ROS 2 so far. So it is not possible to use it in launchfiles or directly.

> Also I wasn't sure where to open this issue - here or in the /launch repo.

The recommended place to ask questions is http://answers.ros.org using the `ros2` tag.
For more details about how to ask question you can refer to the [ROS support guidelines](http://wiki.ros.org/Support)

---

@clalancette @sloretz would you be ok for adding here the same issue template as the other ros2 repositories to redirect users to ROS Answers for questions?

**Comment by mikaelarguedas** [comment]
> it would be much work to transform them all to standard urdf.

@ToRaVe xacro is converting .xacro files into URDF. Would it be possible to just run `xacro` on your files and save + use the resulting URDFs with ROS 2?

**Comment by ghost** [comment]
Thanks for your quick answer. It is possible to convert the files, but it is much more convenient to work with xacro files. Have a nice day (:

**Comment by mikaelarguedas** [comment]
As xacro is not depending on many ROS 1 features it should be possible to use it in ROS 2 without much changes. It looks like some work in that direction has been done in https://github.com/ros/xacro/pull/154 and discussed at https://github.com/osrf/homebrew-simulation/issues/383 as well

**Comment by clalancette** [comment]
> @clalancette @sloretz would you be ok for adding here the same issue template as the other ros2 repositories to redirect users to ROS Answers for questions?

Fine by me.

**Comment by sloretz** [comment]
> @clalancette @sloretz would you be ok for adding here the same issue template as the other ros2 repositories to redirect users to ROS Answers for questions?

#6 , I'll merge it right away.
